import type { Metadata } from "next";

import "./globals.css";
import Nav from "@/Components/Nav";
import { AuthProvider } from "@/context/authContext";
import Dock from "@/Components/Dock";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="synthwave">
      <body className={`antialiased bg-base-200 h-screen`}>
        <AuthProvider>
          <Nav />
          <Dock />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
